
-- V1__Init_Security_Tables.sql

-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
    id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    ref VARCHAR(500) UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_roles_name ON roles(name);

-- Hibernate Envers revision tracking
CREATE TABLE IF NOT EXISTS revinfo (
    rev     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- Create users table with dynamic fields based on configuration
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    ref VARCHAR(500) UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE,
    is_locked BOOLEAN DEFAULT FALSE,
    is_credentials_expired BOOLEAN DEFAULT FALSE,
    is_email_verified BOOLEAN DEFAULT FALSE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Create users_roles join table
CREATE TABLE IF NOT EXISTS users_roles (
    users_id VARCHAR(255) NOT NULL,
    roles_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (users_id, roles_id),
    FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_roles_role_id ON users_roles(roles_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_active ON users(email) WHERE deleted_at IS NULL;

-- Create application entity tables (PostgreSQL, excluding User)
CREATE TABLE IF NOT EXISTS app_hobby (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    cost_tier VARCHAR(255) NOT NULL,
    space_needed VARCHAR(255) NOT NULL,
    time_commitment VARCHAR(255) NOT NULL,
    difficulty VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    content_source VARCHAR(255) NOT NULL,
    last_reviewed_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_hobby_ref ON app_hobby(ref);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_hobby_name_active ON app_hobby(name) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS app_stage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    title VARCHAR(255) NOT NULL,
    "order" NUMERIC(19,2) NOT NULL,
    hobby_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_stage_ref ON app_stage(ref);
CREATE INDEX IF NOT EXISTS idx_app_stage_hobby_id ON app_stage(hobby_id);

CREATE TABLE IF NOT EXISTS app_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    "order" NUMERIC(19,2) NOT NULL,
    estimated_minutes NUMERIC(19,2),
    stage_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_step_ref ON app_step(ref);
CREATE INDEX IF NOT EXISTS idx_app_step_stage_id ON app_step(stage_id);

CREATE TABLE IF NOT EXISTS app_userprogress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    completed BOOLEAN NOT NULL,
    completed_at TIMESTAMP(6),
    user_id VARCHAR(255) NOT NULL,
    step_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_userprogress_ref ON app_userprogress(ref);
CREATE INDEX IF NOT EXISTS idx_app_userprogress_user_id ON app_userprogress(user_id);
CREATE INDEX IF NOT EXISTS idx_app_userprogress_step_id ON app_userprogress(step_id);

CREATE TABLE IF NOT EXISTS app_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    hobby_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_favorite_ref ON app_favorite(ref);
CREATE INDEX IF NOT EXISTS idx_app_favorite_user_id ON app_favorite(user_id);
CREATE INDEX IF NOT EXISTS idx_app_favorite_hobby_id ON app_favorite(hobby_id);

CREATE TABLE IF NOT EXISTS app_achievement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    threshold NUMERIC(19,2) NOT NULL,
    icon_url VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_achievement_ref ON app_achievement(ref);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_achievement_name_active ON app_achievement(name) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS app_userachievement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    earned_at TIMESTAMP(6) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    achievement_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_userachievement_ref ON app_userachievement(ref);
CREATE INDEX IF NOT EXISTS idx_app_userachievement_user_id ON app_userachievement(user_id);
CREATE INDEX IF NOT EXISTS idx_app_userachievement_achievement_id ON app_userachievement(achievement_id);


-- Create join tables for ManyToMany relationships (PostgreSQL)

-- Insert initial roles from configuration
INSERT INTO roles (id, name, created_date, created_by) 
SELECT gen_random_uuid()::text, 'ROLE_ADMIN', NOW(), 'system'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN');

INSERT INTO roles (id, name, created_date, created_by) 
SELECT gen_random_uuid()::text, 'ROLE_USER', NOW(), 'system'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_USER');


