services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Hobbify_dev
      POSTGRES_USER: Hobbify_user
      POSTGRES_PASSWORD: "dev123"
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Hobbify_user -d Hobbify_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app-net

  adminer:
    image: adminer:latest
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net




networks:
  app-net:
    driver: bridge

